/ redirect and index cleanup
hmrc/advance-valuation-rulings-frontend pull request #199
Opened 2023-04-12 14:50 UTC by C-Thomp

index controller and view removed
/ now redirects to home

2023-04-12 15:36 UTC, wolfendale commented on conf/app.routes
> +GET        /                                            controllers.Default.redirect(to = "/advance-valuation-ruling/applications-and-rulings")
Would love to see a test for this. Would also be great if we could get rid of the absolute path.

2023-04-12 16:18 UTC, koladeadewuyi approved these changes

2023-04-13 08:47 UTC, wolfendale requested changes

2023-04-13 09:23 UTC, wolfendale commented on test/navigation/NavigatorSpec.scala
> +        val request = FakeRequest(GET, "/advance-valuation-ruling")
I'm wrong!

2023-04-13 10:40 UTC, wolfendale approved these changes

2023-04-13 10:41 UTC, merged