feat: add save as draft button for upload letter of authority view
hmrc/advance-valuation-rulings-frontend pull request #378
Opened 2023-08-21 15:14 UTC by aaocs

### Type of change
- [ ] Breaking change
- [ ] Non-breaking change
- [ ] Cosmetic change

### Description
Jira link: [Add Save as draft button to Upload Letter of Authority Page(https://jira.tools.tax.service.gov.uk/browse/ARSSTB-326)

Add save as draft button for upload letter of authority view.

### Attachments or Screenshots
![Screenshot 2023-08-21 at 16 13 47](https://github.com/hmrc/advance-valuation-rulings-frontend/assets/132440545/6dba7e38-7f77-428e-a5c6-7e889919aeed)

2023-08-21 16:04 UTC, C-Thomp requested changes
There's a component for this called SaveButtons.scala.html :)
helps reduce repeated html blocks across the service

not to be confused with SaveButtonWithDraft mind 👀

2023-08-22 08:09 UTC, C-Thomp commented
> > 
> 
> The SaveButtons.scala.html includes the submit button. The view modified in this review uses custom logic which disables the submit button, so as far as I'm aware I can't keep that logic if I use the SaveButtons component.
> 
> One option would be to create another component and use that; what do you think?

(Discussed) Disabling both buttons would prevent weird behaviour if a user Drafts while an upload is in progress 👍

2023-08-22 09:30 UTC, paulhargrave approved these changes
:)

2023-08-22 10:52 UTC, C-Thomp approved these changes

2023-08-22 10:57 UTC, merged