added CSRF tokens to supported documents and letter of authority page
hmrc/advance-valuation-rulings-frontend pull request #442
Opened 2023-09-27 10:25 UTC by RobertLaverick

### Type of change
- [ ] Breaking change
- [X] Non-breaking change
- [ ] Cosmetic change

### Description
Jira link: [Use FormWithCSRF in UploadSupportingDocumentsView](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-417)

Added CSRF token using helpers to both UploadSupportingDocumentsView and UploadLetterOfAuthorityView.

2023-09-27 10:35 UTC, paulhargrave requested changes
We need to leave this until after the release

2023-09-27 10:37 UTC, paulhargrave commented
I think I'm just going to close the PR. Looks good though. Do we have to release to staging to see if this resolves our Zap warnings?

2023-09-27 10:38 UTC, RobertLaverick commented
> I think I'm just going to close the PR. Looks good though. Do we have to release to staging to see if this resolves our Zap warnings?

Oh, I wasn't aware we weren't even opening PRs for that. I'd presume so, I've confirmed the tokens are there in the forms though.

2023-09-28 10:59 UTC, aaocs approved these changes

2023-09-28 12:23 UTC, merged