ARSSTB-575 Labels or legends for various pages + bugfixes
hmrc/advance-valuation-rulings-frontend pull request #497
Opened 2023-10-19 08:26 UTC by Ewan-James-Donovan

### Type of change
- [ ] Breaking change
- [x] Non-breaking change
- [ ] Cosmetic change

### Description
Jira link: [Jira title](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-575)

Please refer to the jira ticket.

2023-10-19 09:19 UTC, aaocs commented on conf/messages.cy
>  whyIdenticalGoods.paragraph.2 = Esboniwch pam rydych o’r farn nad yw Dull 1 yn addas i gyfrifo gwerth tollau eich nwyddau.
Remove these two keys if they are no longer used (they have been removed from messages.en)

2023-10-19 09:22 UTC, aaocs requested changes
2 keys to remove from messages.cy, and one question.

2023-10-19 09:43 UTC, Ewan-James-Donovan commented on app/views/ExplainWhyYouHaveNotSelectedMethodOneToFiveView.scala.html
> +                label = LabelViewModel(Text(messages("explainWhyYouHaveNotSelectedMethodOneToFive.label"))).asLegendHeading()
This is 100% intentional, the labels are displayed as the questions, as per gov design system.

2023-10-19 09:43 UTC, Ewan-James-Donovan commented on app/views/ExplainWhyYouHaveNotSelectedMethodOneToFiveView.scala.html
> +                label = LabelViewModel(Text(messages("explainWhyYouHaveNotSelectedMethodOneToFive.label"))).asLegendHeading()
https://design-system.service.gov.uk/get-started/labels-legends-headings/

2023-10-19 09:46 UTC, Ewan-James-Donovan commented on conf/messages.cy
>  whyIdenticalGoods.paragraph.2 = Esboniwch pam rydych o’r farn nad yw Dull 1 yn addas i gyfrifo gwerth tollau eich nwyddau.
Done

2023-10-19 10:46 UTC, aaocs submitted a review, later dismissed

2023-10-20 10:57 UTC, aaocs submitted a review, later dismissed

2023-10-20 11:04 UTC, aaocs approved these changes

2023-10-20 11:14 UTC, merged