ARSSTB-509 Welsh Error Fix
hmrc/advance-valuation-rulings-frontend pull request #513
Opened 2023-10-20 13:28 UTC by Ewan-James-Donovan

### Type of change
- [ ] Breaking change
- [ ] Non-breaking change
- [x] Cosmetic change

2023-10-20 13:33 UTC, aaocs approved these changes

2023-10-20 14:02 UTC, aaocs submitted a review, later dismissed

2023-10-20 14:03 UTC, aaocs submitted a review, later dismissed

2023-10-20 14:45 UTC, aaocs approved these changes

2023-10-20 15:26 UTC, paulhargrave submitted a review, later dismissed

2023-10-20 15:27 UTC, paulhargrave approved these changes

2023-10-20 15:28 UTC, paulhargrave submitted a review, later dismissed

2023-10-23 08:28 UTC, RobertLaverick requested changes

2023-10-23 08:28 UTC, RobertLaverick commented on app/views/AboutSimilarGoodsView.scala.html
> -            maxLength = Some(8000),
why have you changed the maxLength? For one the form provider will kick up a stink if the lengths are different but the ticket this was introduced in specified 8000 characters

2023-10-23 08:28 UTC, RobertLaverick commented on app/views/TellUsAboutYourRulingView.scala.html
> -            .withMaxLength(8000)
Same here

2023-10-23 08:40 UTC, closed without merging