ARSSTB-575 Fixes
hmrc/advance-valuation-rulings-frontend pull request #522
Opened 2023-10-23 13:02 UTC by Ewan-James-Donovan

### Type of change
- [ ] Breaking change
- [ ] Non-breaking change
- [x] Cosmetic change

2023-10-23 13:09 UTC, aaocs approved these changes

2023-10-24 09:48 UTC, aaocs approved these changes

2023-10-24 09:52 UTC, merged

2023-10-24 09:52 UTC, RobertLaverick requested changes

2023-10-24 09:52 UTC, RobertLaverick commented on app/views/ExplainHowYouWillUseMethodSixView.scala.html
> +        <br></br>
Aren't we meant to be removing break tags for accessibility?