DDCE-4866 Amendment to fact check
hmrc/advance-valuation-rulings-frontend pull request #581
Opened 2024-02-23 08:00 UTC by gastonracui

2024-02-23 09:06 UTC, gastonracui commented
details: https://jira.tools.tax.service.gov.uk/browse/DDCE-4866

2024-02-23 09:11 UTC, EdCope requested changes

2024-02-23 09:11 UTC, EdCope commented on conf/messages.cy
> +agentForTraderCheckYourAnswers.heading = Gwirio’ch atebion cyn anfon eich cais
Please match the title key to the new text as well for confirmation you can see 

I'm also wondering if the text we have for other keys like `checkYourAnswers.heading` is now wrong or should be updated too will look further

2024-02-26 14:49 UTC, EdCope approved these changes

2024-02-26 14:49 UTC, merged